name: full_cover
description: Multi-package test coverage for Dart and Flutter workspaces. Merges LCOV data and generates HTML reports.
version: 1.0.0
homepage: https://github.com/llfbandit/full_cover/tree/main/full_cover

topics:
  - testing
  - coverage
  - lcov
  - report

executables:
  full_cover:

resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  path: ^1.9.0
  yaml: ^3.0.0
  args: ^2.6.0
  glob: ^2.1.2
  coverage: ^1.11.1
  analyzer: '>=10.0.0 <15.0.0'

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
